version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-presentai
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - presentai_network

  backend:
    build: .
    container_name: backend-presentai
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-presentai:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - presentai_network

networks:
  presentai_network:
    driver: bridge